### ISSUE TITLE
v1.1.0 Non-functional on new installs or specific existing installs, broken behavior on certain existing installs.

### ISSUE THREAD

**Issue by ZD-ChaofanJ** [Confusified/LC-FramerateSlider#26]
**Tested with the following Mod(s):**
- Framerate_Slider v1.1.0 and BepInExPack v5.4.2100 only.
- Lemon Company Modpack (v8.0.0) by ChaofanJ with Framerate_Slider v1.1.0

**Lethal Company:**
- Tested with Lethal Company v50

**Bug(s)**
When running Framerate_Slider v1.1.0 on a fresh install, the mod simply does not work and the framerate slider does not show up. Only the Vanilla Framerate Settings are visible. When upgrading the mod on certain existing installs or from certain configurations (such as the Lemon Company or similar Modpacks, even if the install is "new"), the slider will somehow showup but has bugged behavior. If the slider was set to (or was previously set to) VSync (all the way left), the game will set the Framerate to 1 FPS instead of using V-Sync.

**Steps to Reproduce Non-Functional Behavior (Framerate_Slider v1.1.0 and BepInExPack v5.4.2100 only.)**
1. Go to Thunderstore Mod Manager (or r2modman).
2. Create a new profile for Lethal Company.
3. Go to the "Gets mods" section.
4. Install Framerate_Slider (v1.1.0) by Confusified.
5. Run the game "Modded".
6. Go to the settings menu and the Slider will not be there, only the default framerate options.

**Steps to Reproduce Broken Behavior (Lemon Company Modpack v8.0.0 + Manual upgrade to Framerate_Slider v1.1.0)**
1. Go to Thunderstore Mod Manager (or r2modman).
2. Create a new profile for Lethal Company.
3. Go to the "Gets mods" section.
4. Install the Lemon Company Modpack (v8.0.0) by ChaofanJ. The version of the Modpack used for testing was specifically v8.0.0.
5. Go to the "My mods" section.
6. Manually update "Framerate_Slider" to v1.1.0 by finding the mod in the list or searching for it and selecting "Update". I would avoid updating any other mods manually (save for Framerate_Slider) for testing purposes.
7. Run the game "Modded".
8. Go to the settings menu and try setting the framerate to "V-Sync".
9. Expect broken framerate behavior and or the game to run at 1 FPS.

**Expected behavior**
1. Open Mod Manager and run the game "Modded".
2. Go to Settings Menu.
3. Find and see the Framerate Slider.
4. Set the Framerate to desired limit/V-Sync.

**Hardware (May not relevant but I will include some of it anyway)**
- Intel Core i9-13900k (Slightly Underclocked and Undervolted).
- MPG Z790 Carbon Wi-Fi (MS-7D89) Motherboard.
- NVIDIA RTX 3090 (24 GB VRAM).
- Lethal Company installed on a Kingston NV2 (SNV2S2000G) 2 TB SSD.

**Comment by ZD-ChaofanJ** [comment]
Temporary Workaround:  Avoid upgrading to v1.1.0 and stay on version v1.0.5 of this mod until the issues are able to be fixed.

**Comment by Confusified** [comment]
Thank you for the report, I've been able to reproduce both issues and I'll upload a patched version shortly

**Comment by Confusified** [comment]
I've updated the mod, it should now work as intended

**Comment by ZD-ChaofanJ** [comment]
Yup. Seems to be working as of v1.1.1.
